"""empty message

Revision ID: 59b8e9626328
Revises: efd2b3b0df4f
Create Date: 2020-05-18 07:06:41.943106

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '59b8e9626328'
down_revision = 'efd2b3b0df4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbEmployee')
    op.add_column('users', sa.Column('EmpId', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('MangId', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'MangId')
    op.drop_column('users', 'EmpId')
    op.create_table('tbEmployee',
    sa.Column('EmployeeId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('EmployeeName', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('ManagerId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('EmployeeId'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
